---
# tasks file for nginx

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  notify:
    - Restart Nginx

- name: Copy Nginx setup files
  ansible.builtin.template:
    src: "{{ nginx_source }}"
    dest: "{{ nginx_dest }}"
    mode: u=rw,g=r,o=r
    validate: nginx -t -c %s
  notify:
    - Restart Nginx

- name: Delete default site
  ansible.builtin.file:
    path: "{{ nginx_path }}"
    state: absent
  notify:
    - Restart Nginx
