---
- name: "Создать группу Loki"
  become: true
  group:
    name: "{{ loki_group }}"
    system: yes
    state: present

- name: "Создать пользователя Loki"
  become: true
  user:
    name: "{{ loki_user.name }}"
    group: "{{ loki_group }}"
    system: yes
    shell: "{{ loki_user.shell }}"

- name: "Изменить владельца директорий Loki"
  become: true
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    recurse: "{{ item.recurse }}"
    owner: "{{ loki_user.name }}"
    group: "{{ loki_group }}"
    mode: '0775'
  with_items:
    - state: file
      path: "{{ loki_bin.dir }}/{{ loki_bin.file }}"
      recurse: no
    - state: directory
      path: "{{ loki_etc_dir }}"
      recurse: yes

- name: "Создать systemd сервис для Loki"
  become: true
  template:
    src: "{{ loki_service.template_path }}"
    dest: "/etc/systemd/system/{{ loki_service.name }}"
  notify: "Start and Enable Loki Service"
