---
# defaults file for postgresql

postgresql_version: 15

postgresql_support_packages:
  - gnupg
  - python3-psycopg2

postgresql_packages:
  - "postgresql-{{ postgresql_version }}"
  - "postgresql-contrib-{{ postgresql_version }}"

postgresql_repo_key: https://www.postgresql.org/media/keys/ACCC4CF8.asc

postgresql_repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
postgresql_repo_filename: pgdg

postgresql_postgres_password: postgres

postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}"
postgresql_config_dir: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_new_data_dir: /tmp/postgresql

users_hba_method: md5
replication_hba_method: md5

postgresql_users:
  - name: root
    password: 123456
    encrypted: true
    role_attr_flags: SUPERUSER
    port: 5432

postgresql_databases:
  - name: postgresqlDB
    port: 5432
    roles: solidbush
    privs: ALL

master_address:
  - 192.168.56.201
replica_address:
  - 192.168.56.202