---
- name: "Клиент | Создание директории для клиентских конфигураций"
  file:
    path: "{{ client_configs_dir }}/keys"
    state: directory
    mode: "0755"

- name: "Клиент | Установка прав доступа только для владельца"
  file:
    path: "{{ client_configs_dir }}"
    mode: "0700"

- name: "Клиент | Создание запроса на подпись клиентского сертификата"
  command:
    cmd: "{{ easy_rsa_binary }}/easyrsa gen-req {{ openvpn_client_name }} nopass"
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/pki/private/{{ openvpn_client_name }}.key"
  environment:
    EASYRSA_BATCH: "yes"

- name: "Клиент | Копирование файлов в {{ client_configs_dir }}/keys/"
  copy:
    src: "{{ easy_rsa_dir }}/pki/private/{{ openvpn_client_name }}.key"
    dest: "{{ client_configs_dir }}/keys/{{ openvpn_client_name }}.key"
    remote_src: "yes"

- name: "Клиент | Копирование запроса сертификата для подписи"
  copy:
    src: "{{ easy_rsa_dir }}/pki/reqs/{{ openvpn_client_name }}.req"
    dest: "/tmp/{{ openvpn_client_name }}.req"
    remote_src: "yes"
