---
- name: "Сервер | Копирование конфигурации OpenVPN"
  become: true
  template:
    src: "{{ openvpn_server_config_template }}"
    dest: "{{ openvpn_server_dir }}/server.conf"
  notify:
    - "Запуск OpenVPN"

- name: "Сервер | Копирование файлов в {{ client_configs_dir }}/keys/"
  copy:
    src: "{{ item }}"
    dest: "{{ client_configs_dir }}/keys/{{ item | basename }}"
    mode: "0640"
    remote_src: "true"
  loop:
    - "/tmp/{{ openvpn_client_name }}.crt"
    - "{{ easy_rsa_dir }}/pki/ta.key"
    - "{{ easy_rsa_dir }}/pki/ca.crt"

- name: "Сервер | Копирование файлов в {{ openvpn_server_dir }}"
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ openvpn_server_dir }}/{{ item | basename }}"
    mode: "0640"
    remote_src: "yes"
  loop:
    - "{{ easy_rsa_dir }}/pki/ta.key"
    - "{{ easy_rsa_dir }}/pki/dh.pem"
    - "{{ easy_rsa_dir }}/pki/crl.pem"
    - "{{ easy_rsa_dir }}/pki/private/{{ openvpn_server_name }}.key"
    - "/tmp/{{ openvpn_server_name }}.crt"
    - "/tmp/ca.crt"

- name: "Клиент | Получение конфигурации клиента"
  fetch:
    src: "{{ client_configs_dir }}/files/{{ openvpn_client_name }}.ovpn"
    dest: "{{ playbook_dir }}/ovpn-client-conf/{{ inventory_hostname }}-{{ openvpn_client_name }}.ovpn"
    flat: true
