---
- name: "Сервер | Установка пакетов"
  become: true
  apt:
    name:
      - openvpn
      - easy-rsa
    state: "present"
    update_cache: "yes"

- name: "Сервер | Добавление переменных для CA"
  template:
    src: "{{ easy_rsa_vars_template }}"
    dest: "{{ easy_rsa_dir }}/vars"

- name: "Сервер | Инициализация PKI"
  command:
    cmd: "{{ easy_rsa_binary }}/easyrsa init-pki"
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/pki"

- name: "Сервер | Создание Diffie-Hellman.pem"
  command:
    cmd: "{{ easy_rsa_binary }}/easyrsa gen-dh"
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/pki/dh.pem"

- name: "Сервер | Создание crl.pem"
  command:
    cmd: "{{ easy_rsa_binary }}/easyrsa gen-crl"
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/pki/crl.pem"

- name: "Сервер | HMAC tls-crypt"
  command:
    cmd: "openvpn --genkey --secret {{ easy_rsa_dir }}/pki/ta.key"
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/pki/ta.key"

- name: "Сервер | Создание запроса для подписания сертификата сервера"
  command:
    cmd: "{{ easy_rsa_binary }}/easyrsa gen-req {{ openvpn_server_name }} nopass"
    chdir: "{{ easy_rsa_dir }}"
    creates: "{{ easy_rsa_dir }}/pki/reqs/{{ openvpn_server_name }}.req"
  environment:
    EASYRSA_BATCH: "yes"

- name: "Сервер | Копирование запроса на сертификат для подписи"
  copy:
    src: "{{ easy_rsa_dir }}/pki/reqs/{{ openvpn_server_name }}.req"
    dest: "/tmp/{{ openvpn_server_name }}.req"
    remote_src: "yes"
